name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Dependency Review
        uses: actions/dependency-review-action@v4

  security-scans:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trivy filesystem scan
        id: trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: 1
          format: sarif
          output: trivy-results.sarif
        continue-on-error: true

      - name: Upload Trivy SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
          category: trivy

      - name: Fail on Trivy findings
        if: steps.trivy.outcome == 'failure'
        run: |
          echo "Trivy found CRITICAL/HIGH vulnerabilities"
          exit 1

      - name: Semgrep SAST scan
        id: semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: p/ci
          format: sarif
          output: semgrep-results.sarif
        continue-on-error: true

      - name: Upload Semgrep SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif
          category: semgrep

      - name: Fail on Semgrep findings
        if: steps.semgrep.outcome == 'failure'
        run: |
          echo "Semgrep reported findings"
          exit 1

  codeql:
    needs: security-scans
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp

      - name: Restore solution
        run: dotnet restore QRTracker.sln

      - name: Build for CodeQL
        run: dotnet build src/QRTracker/QRTracker.csproj -c Debug

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  build:
    needs: security-scans
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore QRTracker.sln

      - name: Vulnerability scan (dotnet list package)
        run: dotnet list src/QRTracker/QRTracker.csproj package --vulnerable --include-transitive

      - name: Install dotnet-audit tool
        shell: pwsh
        run: |
          dotnet tool update --global dotnet-audit --no-cache || dotnet tool install --global dotnet-audit

      - name: Vulnerability audit (dotnet audit)
        shell: pwsh
        run: |
          $env:PATH += ';' + (Join-Path $env:USERPROFILE '.dotnet\tools')
          dotnet audit src/QRTracker/QRTracker.csproj --framework net9.0-windows10.0.19041.0 --ignore-failed-sources

      - name: Deprecated package scan
        run: dotnet list src/QRTracker/QRTracker.csproj package --deprecated

      - name: License compliance check
        shell: pwsh
        run: |
          dotnet list src/QRTracker/QRTracker.csproj package --include-transitive --license > licenses.txt
          Get-Content licenses.txt
          if (Select-String -Path licenses.txt -Pattern 'AGPL|GPL|LGPL|UNKNOWN|UNLICENSED') {
            Write-Error 'Disallowed or unknown licenses detected.'
            exit 1
          }
        working-directory: ${{ github.workspace }}

      - name: Upload license report
        uses: actions/upload-artifact@v4
        with:
          name: license-report
          path: licenses.txt

      - name: Install Gitleaks
        shell: pwsh
        run: choco install gitleaks --no-progress -y

      - name: Credential leak scan (gitleaks)
        shell: pwsh
        run: |
          $env:PATH += ';C:\ProgramData\chocolatey\bin'
          gitleaks detect --source "${{ github.workspace }}" --no-banner --redact

      - name: Build (Release)
        run: dotnet build src/QRTracker/QRTracker.csproj -c Release

      - name: Publish self-contained executable
        shell: pwsh
        run: |
          $publishDir = Join-Path $env:GITHUB_WORKSPACE 'artifacts/win-x64'
          New-Item -ItemType Directory -Force -Path $publishDir | Out-Null
          dotnet publish src/QRTracker/QRTracker.csproj -c Release -f net9.0-windows10.0.19041.0 -r win10-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:EnableCompressionInSingleFile=true -o $publishDir
          Get-ChildItem $publishDir

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: QRTracker-win-x64
          path: artifacts/win-x64/*.exe

  release:
    needs:
      - build
      - codeql
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: QRTracker-win-x64
          path: dist

      - name: Rename binary with tag
        run: |
          mv dist/QRTracker.exe dist/QRTracker-${{ github.ref_name }}.exe

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/QRTracker-${{ github.ref_name }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
